language: node_js
node_js:
- "node"
before_install:
- npm config set spin false
- npm i -g makeshift && makeshift -r https://registry.npmjs.org
install:
- yarn
script:
- yarn build
- yarn test
deploy:
  - provider: npm
    skip_cleanup: true
    email: kchau@microsoft.com
    api_key: $NPM_TOKEN
    tag: latest
    on:
      tags: true
      condition: >
        "$TRAVIS_TAG" != *"-"*
  - provider: npm
    skip_cleanup: true
    email: kchau@microsoft.com
    api_key: $NPM_TOKEN
    tag: next
    on:
      tags: true
      condition: >
        "$TRAVIS_TAG" == *"-"*
